name: Build & Push Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate .npmrc to use private packages
        uses: healthplace/npmrc-registry-login-action@v1.0
        with:
          scope: "@welovesquad"
          registry: "https://npm.pkg.github.com"
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
          path: ${{ runner.temp }}
      - name: Docker extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secret-files: |
            npmrc=${{ runner.temp }}/.npmrc
